// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/playlist_entity.dart';
import 'models/video_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 3612528422872712966),
    name: 'PlaylistEntity',
    lastPropertyId: const obx_int.IdUid(9, 5883016639435139532),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4977164647512234155),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6271165634358552847),
        name: 'playlistId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 4801561798544534571),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2488082040811598803),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4526680747102070058),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2520614169662659064),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7639809708974295834),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6687177440365240327),
        name: 'currentIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2306970702510217372),
        name: 'isShuffled',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5883016639435139532),
        name: 'isRepeating',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 8781902076782293056),
        name: 'videos',
        targetId: const obx_int.IdUid(2, 672316015616111791),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 672316015616111791),
    name: 'VideoEntity',
    lastPropertyId: const obx_int.IdUid(11, 8739202298765621945),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1076182216544499371),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4431050747783652597),
        name: 'videoId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 4014387767884565287),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1539502346231496582),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5174752423455655402),
        name: 'duration',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7167742695213152992),
        name: 'subtitle',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6664237108750314908),
        name: 'sourcesJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6407685871508356817),
        name: 'currentServerId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5564068995714249026),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8654554614712483673),
        name: 'poster',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 8739202298765621945),
        name: 'thumbnailPath',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 672316015616111791),
    lastIndexId: const obx_int.IdUid(2, 4014387767884565287),
    lastRelationId: const obx_int.IdUid(1, 8781902076782293056),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [7501353072104872199],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    PlaylistEntity: obx_int.EntityDefinition<PlaylistEntity>(
      model: _entities[0],
      toOneRelations: (PlaylistEntity object) => [],
      toManyRelations: (PlaylistEntity object) => {
        obx_int.RelInfo<PlaylistEntity>.toMany(1, object.id): object.videos,
      },
      getId: (PlaylistEntity object) => object.id,
      setId: (PlaylistEntity object, int id) {
        object.id = id;
      },
      objectToFB: (PlaylistEntity object, fb.Builder fbb) {
        final playlistIdOffset = fbb.writeString(object.playlistId);
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, playlistIdOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, descriptionOffset);
        fbb.addInt64(4, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(5, object.updatedAt.millisecondsSinceEpoch);
        fbb.addInt64(6, object.currentIndex);
        fbb.addBool(7, object.isShuffled);
        fbb.addBool(8, object.isRepeating);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final playlistIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final object =
            PlaylistEntity(
                playlistId: playlistIdParam,
                name: nameParam,
                description: descriptionParam,
                createdAt: createdAtParam,
                updatedAt: updatedAtParam,
              )
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
              ..currentIndex = const fb.Int64Reader().vTableGet(
                buffer,
                rootOffset,
                16,
                0,
              )
              ..isShuffled = const fb.BoolReader().vTableGet(
                buffer,
                rootOffset,
                18,
                false,
              )
              ..isRepeating = const fb.BoolReader().vTableGet(
                buffer,
                rootOffset,
                20,
                false,
              );
        obx_int.InternalToManyAccess.setRelInfo<PlaylistEntity>(
          object.videos,
          store,
          obx_int.RelInfo<PlaylistEntity>.toMany(1, object.id),
        );
        return object;
      },
    ),
    VideoEntity: obx_int.EntityDefinition<VideoEntity>(
      model: _entities[1],
      toOneRelations: (VideoEntity object) => [],
      toManyRelations: (VideoEntity object) => {},
      getId: (VideoEntity object) => object.id,
      setId: (VideoEntity object, int id) {
        object.id = id;
      },
      objectToFB: (VideoEntity object, fb.Builder fbb) {
        final videoIdOffset = fbb.writeString(object.videoId);
        final titleOffset = fbb.writeString(object.title);
        final subtitleOffset = object.subtitle == null
            ? null
            : fbb.writeString(object.subtitle!);
        final sourcesJsonOffset = fbb.writeString(object.sourcesJson);
        final currentServerIdOffset = object.currentServerId == null
            ? null
            : fbb.writeString(object.currentServerId!);
        final posterOffset = object.poster == null
            ? null
            : fbb.writeString(object.poster!);
        final thumbnailPathOffset = object.thumbnailPath == null
            ? null
            : fbb.writeString(object.thumbnailPath!);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, videoIdOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addInt64(4, object.duration);
        fbb.addOffset(5, subtitleOffset);
        fbb.addOffset(6, sourcesJsonOffset);
        fbb.addOffset(7, currentServerIdOffset);
        fbb.addInt64(8, object.createdAt.millisecondsSinceEpoch);
        fbb.addOffset(9, posterOffset);
        fbb.addOffset(10, thumbnailPathOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final videoIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final posterParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final thumbnailPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final durationParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final subtitleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final currentServerIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
        );
        final object =
            VideoEntity(
                videoId: videoIdParam,
                title: titleParam,
                poster: posterParam,
                thumbnailPath: thumbnailPathParam,
                duration: durationParam,
                subtitle: subtitleParam,
                currentServerId: currentServerIdParam,
                createdAt: createdAtParam,
              )
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
              ..sourcesJson = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGet(buffer, rootOffset, 16, '');

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [PlaylistEntity] entity fields to define ObjectBox queries.
class PlaylistEntity_ {
  /// See [PlaylistEntity.id].
  static final id = obx.QueryIntegerProperty<PlaylistEntity>(
    _entities[0].properties[0],
  );

  /// See [PlaylistEntity.playlistId].
  static final playlistId = obx.QueryStringProperty<PlaylistEntity>(
    _entities[0].properties[1],
  );

  /// See [PlaylistEntity.name].
  static final name = obx.QueryStringProperty<PlaylistEntity>(
    _entities[0].properties[2],
  );

  /// See [PlaylistEntity.description].
  static final description = obx.QueryStringProperty<PlaylistEntity>(
    _entities[0].properties[3],
  );

  /// See [PlaylistEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<PlaylistEntity>(
    _entities[0].properties[4],
  );

  /// See [PlaylistEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<PlaylistEntity>(
    _entities[0].properties[5],
  );

  /// See [PlaylistEntity.currentIndex].
  static final currentIndex = obx.QueryIntegerProperty<PlaylistEntity>(
    _entities[0].properties[6],
  );

  /// See [PlaylistEntity.isShuffled].
  static final isShuffled = obx.QueryBooleanProperty<PlaylistEntity>(
    _entities[0].properties[7],
  );

  /// See [PlaylistEntity.isRepeating].
  static final isRepeating = obx.QueryBooleanProperty<PlaylistEntity>(
    _entities[0].properties[8],
  );

  /// see [PlaylistEntity.videos]
  static final videos = obx.QueryRelationToMany<PlaylistEntity, VideoEntity>(
    _entities[0].relations[0],
  );
}

/// [VideoEntity] entity fields to define ObjectBox queries.
class VideoEntity_ {
  /// See [VideoEntity.id].
  static final id = obx.QueryIntegerProperty<VideoEntity>(
    _entities[1].properties[0],
  );

  /// See [VideoEntity.videoId].
  static final videoId = obx.QueryStringProperty<VideoEntity>(
    _entities[1].properties[1],
  );

  /// See [VideoEntity.title].
  static final title = obx.QueryStringProperty<VideoEntity>(
    _entities[1].properties[2],
  );

  /// See [VideoEntity.duration].
  static final duration = obx.QueryIntegerProperty<VideoEntity>(
    _entities[1].properties[3],
  );

  /// See [VideoEntity.subtitle].
  static final subtitle = obx.QueryStringProperty<VideoEntity>(
    _entities[1].properties[4],
  );

  /// See [VideoEntity.sourcesJson].
  static final sourcesJson = obx.QueryStringProperty<VideoEntity>(
    _entities[1].properties[5],
  );

  /// See [VideoEntity.currentServerId].
  static final currentServerId = obx.QueryStringProperty<VideoEntity>(
    _entities[1].properties[6],
  );

  /// See [VideoEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<VideoEntity>(
    _entities[1].properties[7],
  );

  /// See [VideoEntity.poster].
  static final poster = obx.QueryStringProperty<VideoEntity>(
    _entities[1].properties[8],
  );

  /// See [VideoEntity.thumbnailPath].
  static final thumbnailPath = obx.QueryStringProperty<VideoEntity>(
    _entities[1].properties[9],
  );
}
