name: video_stream_player
description: "A network streaming video player for Ubuntu"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.3
  chewie: ^1.13.0
  cupertino_icons: ^1.0.6
  fvp: ^0.35.2
  shared_preferences: ^2.5.4
  objectbox: ^5.2.0
  objectbox_flutter_libs: any
  path_provider: ^2.1.5
  path: ^1.9.1
  http: ^1.6.0
  video_thumbnail: ^0.5.6
  responsive_framework: ^1.5.1
  animations: ^2.1.1
  flutter_animate: ^4.5.2
  window_manager: ^0.5.1
  bitsdojo_window: ^0.1.6
  desktop_drop: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.11.1
  objectbox_generator: any

flutter:
  uses-material-design: true
